# @package habitat.dataset
defaults:
  - /habitat/dataset: dataset_config_schema
  - _self_

type: ObjectNav-v1
split: train
# data_path: data/datasets/objectnav/hm3d/v1/{split}/{split}.json.gz
# NOTE: MODIFIED LOCALLY HERE FOR NOW, SO I ahve Hm3d V2 used
data_path: data/datasets/objectnav/hm3d/v2/{split}/{split}.json.gz
